name: nightly
on:
  # Triggers the workflow every day at 23:00.
  schedule:
    - cron: '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Environment variables
    env:
      # GOPATH is the current directory.
      GOPATH: ${{ github.workspace }}
      # Turn off modules because they are broken.
      GO111MODULE: off
      WEBBOOT_DISTRO: ${{ matrix.distro }}

    # Set the working directory to the correct place in $GOPATH.
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    strategy:
      matrix:
        distro:
          - Arch
          - CentOS 7
          - CentOS 8
          - Debian
          - Fedora
          - Kali
          - Linux Mint
          - Manjaro
          - Tinycore
          - LHSCowboys
          - DHSGaels
          - Ubuntu
    # Steps represent a sequence of tasks that will be executed as part of the
    # job
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      - name: Checkout dependencies
        run: |
          ./firsttime.sh
      - name: Build and test webboot
        run: |
          ./ci.sh
      - name: Test TestScript
        run: |
          ./nightly.sh
